contactapp/urls.py
from django.urls import path

from .views import SuccessView, ContactView, AboutProductView



app_name="contactapp"
urlpatterns = [
    path("", ContactView.as_view(), name="contact"),
    path("success/", SuccessView.as_view(), name="success"),
    path("aboutproducts/", AboutProductView.as_view(), name='aboutproduct')
]

products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    # ex: /products/
    path("products/", views.IndexView.as_view(), name="index"),
    # ex: /products/5/
    path("products/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("about/", views.about, name="about" ),
    # path("contact/", views.contact, name="contact"),
    path("", views.HomeView.as_view(), name="home"),
    path("products/search", views.SearchResultsView.as_view(), name="search"),

]

store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("products.urls")),
    path("admin/", admin.site.urls),
    path("contact/", include("contactapp.urls")),

]

products/models.py
from django.db import models

# Create your models here.

''' lets create a product model here, it should have the following

-Title
-Description
-image
-sku
-upc
-Measurements (inches)
-Weight (pounds) 
-Cost
-Price




'''

class Category(models.Model):
    name_text = models.CharField("Category Name", max_length= 75)

    def __str__(self):
        return self.name_text

class ProductInfo (models.Model):

    title_text = models.CharField ("Title" , max_length = 200)
    description_text = models.TextField ("Description", max_length = 5000)
    sku_text = models.CharField ("SKU", default = 'noSku', max_length = 20)
    upc_text = models.CharField ("UPC", default = 'noUpc', max_length = 15)
    cost_number = models.FloatField ("Cost", default = 0)
    price_number = models.FloatField ("Price", default = 0)
    CONDITIONS = {
        "BN" : "Brand New",
        "LN" : "Like New",
        "AC" : "Acceptable",
        "DA" : "Damage",
        "MP" : "Missing Parts",
    }
    condition = models.CharField ("Condition", default = "LN",max_length = 20, choices = CONDITIONS)
    storage_number = models.IntegerField("Storage Number", default = 0)
    rack_number = models.IntegerField("Rack number",default = 0)
    item_number = models.IntegerField("Item number", default = 0)
    show_onstore = models.BooleanField("Show in store?",default = True)
    quantity = models.IntegerField("Quatity",default = 0)
    category = models.ManyToManyField(Category)
    


    #location #bodega y rack 

    def __str__(self):
        return self.title_text
    


class Images(models.Model):
    image_url = models.ImageField()
    alt_text = models.CharField(max_length=255)
    onProduct = models.ForeignKey(ProductInfo, related_name = "images", on_delete= models.CASCADE)

products/forms.py
from django import forms

products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from .models import ProductInfo
from django.views import generic
from django.urls import reverse
from django.db.models import Q
from contactapp.forms import AboutProduct
from django.core.mail import send_mail
from django.conf import settings



# Create your views here.


class IndexView(generic.ListView):

    template_name = "products/index.html"
    context_object_name = "products_list"
    paginate_by = 12
        

    def get_queryset(self):
        """Return the objects that are set as show_onstore = TRUE on the database"""
        return ProductInfo.objects.filter(show_onstore=True).order_by('-pk')
        
    
#view for the home
    
class HomeView(generic.ListView):
    template_name = "products/home.html"
    context_object_name = "latest_products"

    def get_queryset(self):
        """Return all the objects that are set as show_onstore = TRUE on the database"""
        return ProductInfo.objects.filter(show_onstore=True).order_by('-pk')[:5]

class DetailView(generic.DetailView):
    model = ProductInfo
    template_name = "products/detail.html"
    context_object_name = 'productinfo'
     

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AboutProduct()
        return context
    
    def post(self, request, *args, **kwargs):
        form = AboutProduct(request.POST)
        product = self.get_object()
        if form.is_valid():
            # Process the form data
            email = form.cleaned_data.get("email")
            subject = form.cleaned_data.get("subject")
            message = form.cleaned_data.get("message")
            
            full_message = f"""
            Received message below from {email}, {subject}, 
            Regarding your product: {product.title_text}
            ________________________


            {message}
            """
            # Send email
            send_mail(
                subject="Received contact form submission",
                message=full_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=settings.NOTIFY_EMAIL,
            )
            # Redirect or signal in some way that the message was sent
            return redirect('contactapp:success')  # Change to an appropriate URL

        # If form is not valid, return to the same detail page with errors
        self.object = self.get_object()
        context = self.get_context_data(object=self.object, contact_form=form)
        return self.render_to_response(context)


def about(request):
    return render(request, "products/about.html", {}) #products/about its the path on the file, not the url

def contact(request):
    return render(request, "products/contact.html", {})

def home(request):
    return render(request, "products/home.html", {})


class SearchResultsView(generic.ListView):
    model = ProductInfo
    template_name = "products/search.html"
    paginate_by = 15

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get("q")
        object_list = ProductInfo.objects.filter(Q(title_text__icontains = query) | Q(category__name_text__icontains = query))
        object_list_show = object_list.filter(show_onstore=True)
        return object_list_show
    

products/templates/products/components/footer.html
{% load static %} <link rel="stylesheet" href="{% static "css/output.css" %}">

<footer class="bg-white rounded-lg shadow m-4 dark:bg-gray-800">
  <div
    class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between"
  >
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">
      <a href="/" class="hover:underline">Etenda</a>. Etenda is an online home goods, furniture, arts and more store. Contact us <a href="/contact">here </a>or in the contact
      us page to arrange an appointment
    </span>
    <ul
      class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0"
    >
      <li>
        <a href="{% url 'products:home'%}" class="hover:underline me-4 md:me-6">Home</a>
      </li>
      <li>
        <a href="{% url 'products:index'%}" class="hover:underline me-4 md:me-6">Products</a>
      </li>
      <li>
        <a href="{% url 'contactapp:contact'%}" class="hover:underline me-4 md:me-6">Contact</a>
      </li>
      <li>
        <a href="{% url 'products:about'%}" class="hover:underline">About</a>
      </li>
    </ul>
  </div>
</footer>

products/templates/products/components/header.html
{% load static %}

<link rel="stylesheet" href="{% static "css/output.css" %}">

<header>
<nav class="bg-[white] border-gray-200 dark:bg-[#001d39]">
    <div class="max-w-screen-xl grid grid-cols-2 items-center md:grid-cols-4 mx-auto p-4">
    <a href="/" class="border-solid border-blue-900 flex items-center space-x-3 rtl:space-x-reverse">
        {% comment %} <img src="{% static "images/favicon.svg" %}" class="h-8" alt="Etenda Logo"> {% endcomment %}
        <img src="{% static "images/etendalogo.jpeg" %}" alt="Etenda Logo" class="w-[10rem]">
    </a>
    <div class="flex md:order-2 ml-auto">
      <button id="theme-toggle" type="button" class="ml-2 w-9 h-9 md:order-last block p-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm" aria-label="light/dark theme button">
        <svg id="theme-toggle-dark-icon" class="m-auto hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
        <svg id="theme-toggle-light-icon" class="m-auto hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
      </button>
        <form action="{% url 'products:search' %}" method="get">
            <div class="relative hidden md:block md:mr-auto">
                <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                </svg>
                <span class="sr-only">Search icon</span>
                </div>
                <input  name="q" type="text" id="search-navbar" class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
            </div>
            </form>
            <button onclick="openNav()" data-collapse-toggle="navbar-search" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-search" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        
    </div>
    
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1 md:mx-auto col-span-4 md:col-span-2" id="navbar-search">
        <div class="relative mt-3 md:hidden">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
            </svg>
          </div>
          <form action="{% url 'products:search' %}" method="get">
          <input name="q" type="text" id="search-navbar" class="block w-full p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
          </form>
        </div>
        <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-[white] md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-[white] dark:bg-[#001d39] md:dark:bg-[#001d39] dark:border-gray-700">
          <li>
            <a href="{% url 'products:home'%}" class="block py-2 px-3 text-black rounded hover:bg-blue-600 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Home</a>
          </li>
          <li>
            <a href="{% url 'products:index'%}" class="block py-2 px-3 text-black rounded hover:bg-blue-600 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Products</a>
          </li>
          <li>
            <a href="{% url 'contactapp:contact'%}" class="block py-2 px-3 text-black rounded hover:bg-blue-600 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact Us</a>
          </li>
          <li>
            <a href="{% url 'products:about'%}" class="block py-2 px-3 text-black rounded hover:bg-blue-600 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
          </li>

        </ul>
      </div>
      
    </div>
    
  </nav>
</header>

<script src="{%static "javascript/header.js"%}"></script>