products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    # ex: /products/
    path("products/", views.IndexView.as_view(), name="index"),
    # ex: /products/5/
    path("products/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("about/", views.about, name="about" ),
    # path("contact/", views.contact, name="contact"),
    path("", views.HomeView.as_view(), name="home"),
    path("products/search", views.SearchResultsView.as_view(), name="search"),

]

store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("products.urls")),
    path("admin/", admin.site.urls),
    path("contact/", include("contactapp.urls")),

]

products/models.py
from django.db import models

# Create your models here.

''' lets create a product model here, it should have the following

-Title
-Description
-image
-sku
-upc
-Measurements (inches)
-Weight (pounds) 
-Cost
-Price




'''

class Category(models.Model):
    name_text = models.CharField("Category Name", max_length= 75)

    def __str__(self):
        return self.name_text

class ProductInfo (models.Model):

    title_text = models.CharField ("Title" , max_length = 200)
    description_text = models.TextField ("Description", max_length = 5000)
    sku_text = models.CharField ("SKU", default = 'noSku', max_length = 20)
    upc_text = models.CharField ("UPC", default = 'noUpc', max_length = 15)
    cost_number = models.FloatField ("Cost", default = 0)
    price_number = models.FloatField ("Price", default = 0)
    CONDITIONS = {
        "BN" : "Brand New",
        "LN" : "Like New",
        "AC" : "Acceptable",
        "DA" : "Damage",
        "MP" : "Missing Parts",
    }
    condition = models.CharField ("Condition", default = "LN",max_length = 20, choices = CONDITIONS)
    storage_number = models.IntegerField("Storage Number", default = 0)
    rack_number = models.IntegerField("Rack number",default = 0)
    item_number = models.IntegerField("Item number", default = 0)
    show_onstore = models.BooleanField("Show in store?",default = True)
    quantity = models.IntegerField("Quatity",default = 0)
    category = models.ManyToManyField(Category)
    


    #location #bodega y rack 

    def __str__(self):
        return self.title_text
    


class Images(models.Model):
    image_url = models.ImageField()
    alt_text = models.CharField(max_length=255)
    onProduct = models.ForeignKey(ProductInfo, related_name = "images", on_delete= models.CASCADE)

products/forms.py
from django import forms

products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from .models import ProductInfo
from django.views import generic
from django.urls import reverse
from django.db.models import Q
from contactapp.forms import AboutProduct
from django.core.mail import send_mail
from django.conf import settings



# Create your views here.


class IndexView(generic.ListView):

    template_name = "products/index.html"
    context_object_name = "products_list"
    paginate_by = 12
        

    def get_queryset(self):
        """Return the objects that are set as show_onstore = TRUE on the database"""
        return ProductInfo.objects.filter(show_onstore=True).order_by('-pk')
        
    
#view for the home
    
class HomeView(generic.ListView):
    template_name = "products/home.html"
    context_object_name = "latest_products"

    def get_queryset(self):
        """Return all the objects that are set as show_onstore = TRUE on the database"""
        return ProductInfo.objects.filter(show_onstore=True).order_by('-pk')[:5]

class DetailView(generic.DetailView):
    model = ProductInfo
    template_name = "products/detail.html"
    context_object_name = 'productinfo'
     

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AboutProduct()
        return context
    
    def post(self, request, *args, **kwargs):
        form = AboutProduct(request.POST)
        product = self.get_object()
        if form.is_valid():
            # Process the form data
            email = form.cleaned_data.get("email")
            subject = form.cleaned_data.get("subject")
            message = form.cleaned_data.get("message")
            
            full_message = f"""
            Received message below from {email}, {subject}, 
            Regarding your product: {product.title_text}
            ________________________


            {message}
            """
            # Send email
            send_mail(
                subject="Received contact form submission",
                message=full_message,
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=settings.NOTIFY_EMAIL,
            )
            # Redirect or signal in some way that the message was sent
            return redirect('contactapp:success')  # Change to an appropriate URL

        # If form is not valid, return to the same detail page with errors
        self.object = self.get_object()
        context = self.get_context_data(object=self.object, contact_form=form)
        return self.render_to_response(context)


def about(request):
    return render(request, "products/about.html", {}) #products/about its the path on the file, not the url

def contact(request):
    return render(request, "products/contact.html", {})

def home(request):
    return render(request, "products/home.html", {})


class SearchResultsView(generic.ListView):
    model = ProductInfo
    template_name = "products/search.html"
    paginate_by = 15

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get("q")
        object_list = ProductInfo.objects.filter(Q(title_text__icontains = query) | Q(category__name_text__icontains = query))
        object_list_show = object_list.filter(show_onstore=True)
        return object_list_show
    

products/templates/products/about.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>LocalxDEstendeal</title>
    <meta
      name="description"
      content="Welcome to Our Website, Your Go-To Destination for Exceptional Finds and Unbeatable Prices! Learn about our journey, mission, and promises to you, our valued customers. Join our growing community of savvy shoppers and explore our diverse collection today!"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static "css/output.css"%}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <script is:inline>
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      ) {
        document.documentElement.classList.add("dark");
      } else {
        document.documentElement.classList.remove("dark");
      }
    </script>
  </head>
  <body class="dark:bg-gradient-to-b dark:from-[#001d39] dark:to-black">
    {% include "products/components/header.html" %}

    <section class="p-2 max-w-4xl mx-auto my-2">
      <div class="mt-10 mb-20">
        <h1
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
        >
          About us
        </h1>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          Welcome to our website, Your Go-To Destination for Exceptional Finds
          and Unbeatable Prices! In the heart of River Grove, there's a
          closely-knit family that dreamed to bring a unique—a place where
          high-quality meets affordability, with a sprinkle of love and
          dedication. We are still hardworking for make this true, a curated
          marketplace that embarks on a mission to bring products at prices that
          keep your wallet happy.
        </p>
      </div>
      <div class="mb-20">
        <h2
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
        >
          Our Journey
        </h2>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          It all started with a simple observation: Why does shopping for
          quality products have to mean breaking the bank? With that question in
          mind, we set out to provide a solution. We decided to leverage our
          passion for finding the best deals and our knack for selecting a
          diverse array of products to offer them to you, our valued customers.
        </p>
      </div>
      <div class="mb-20">
        <h2
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
        >
          Our Mission
        </h2>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          At our Website, we believe that everyone deserves to find their
          desired products without wrestling with hefty price tags. Our mission
          is simple yet profound—to handpick an assortment of exceptional
          products that cater to various needs and interests, and bring them to
          you at prices that can't be beaten. Our commitment goes beyond just
          savings; it's about creating a shopping experience that's both
          rewarding and delightful, where quality and care go hand in hand.
        </p>
      </div>
      <div class="mb-20">
        <h2
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
        >
          Our Promise to You
        </h2>
        <p
          class="mb-3 lg:mb-3 font-light text-gray-500 dark:text-gray-400 sm:text-xl"
        >
          We understand that at the heart of every purchase is a trust that we
          strive to build and maintain. Here's what we promise to our wonderful
          customers:
        </p>
        <ul>
          <li
            class="mb-2 lg:mb-2 font-light text-gray-500 dark:text-gray-400 sm:text-xl"
          >
            <span class="font-bold">Family-first Service:</span> As a family-run
            hobby, we treat every customer as part of our extended family. You
            can expect friendly, personal, and attentive service every time you
            shop with us.
          </li>
          <li
            class="mb-2 lg:mb-2 font-light text-gray-500 dark:text-gray-400 sm:text-xl"
          >
            <span class="font-bold">Unbeatable Prices:</span> Our unique
            approach allows us to offer you some of the best deals on the
            market. We're here to make sure you get more bang for your buck,
            without compromising on quality.
          </li>
          <li class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
            <span class="font-bold">Exceptional Quality:</span> Every product in
            our collection is carefully selected and checked before sale to
            ensure it meets our high standards for quality. We're about making
            sure that you are delighted with every purchase. If you find any
            problem with your sale we will make sure to fix it
          </li>
        </ul>
      </div>
      <div class="mb-20">
        <h2
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
        >
          The Future is Bright
        </h2>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          We are just starting: we're a growing community of savvy shoppers who
          appreciate the value of a dollar and the importance of quality. As we
          continue to grow, our commitment to affordable shopping, customer
          care, and fostering a positive shopping environment remains steadfast.
        </p>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          Looking forward, we are excited to keep expanding our product range,
          embracing more sustainable practices, and finding new ways to give
          back to the community that has supported us since day one.
        </p>
      </div>
      <div class="mb-20">
        <h2
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
        >
          Join Our Family
        </h2>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          We invite you to explore our diverse collection and discover why so
          many have chosen us as their trusted partner for amazing deals.
          Whether you're a long-time customer or just stumbled upon us today, we
          welcome you with open arms to our family.
        </p>
        <p class="font-light text-gray-500 dark:text-gray-400 sm:text-xl">
          Let's embark on this journey together, where great finds meet great
          prices. Welcome to our place, where shopping feels like coming home.
        </p>
      </div>
    </section>

    {%include "products/components/footer.html"%}
  </body>
</html>

products/templates/products/detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Etenda Store</title>
    <meta
      name="description"
      content="Discover the {{productinfo.title_text}}, {{productinfo.description_text}}. Explore its key features, benefits, and specifications."
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link rel="stylesheet" href="{% static "css/output.css"%}">
   <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <script is:inline>
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      ) {
        document.documentElement.classList.add("dark");
      } else {
        document.documentElement.classList.remove("dark");
      }
    </script>
  </head>
  <body class="dark:bg-gradient-to-b dark:from-[#001d39] dark:to-black">
    {% include "products/components/header.html" %}

    <section class="max-w-4xl mx-auto p-2 my-4">
      {% if productinfo.show_onstore == True%}

      <h1
        class="text-2xl md:text-4xl font-bold mx-auto text-center my-2 lg:mb-8 dark:text-white"
      >
        {{productinfo.title_text}}
      </h1>

      {% if productinfo.images.all %}
      <div class="grid gap-4 mb-3">
        <div>
          <img
            id="mainImage"
            class="w-[400px] h-[400px] max-w-full rounded-lg mx-auto"
            src="{{MEDIA_URL}}{{productinfo.images.all.0.image_url}}"
            alt=""
          />
        </div>
        <div
          class="max-w-lg md:max-w-4xl flex flex-row whitespace-nowrap overflow-x-auto mx-auto gap-3"
        >
          {% for image in productinfo.images.all %}
          <div class="min-w-[200px] h-[200px] inline-block">
            <img
              class="h-full max-w-full rounded-lg mx-auto"
              src="{{MEDIA_URL}}{{image.image_url}}"
              alt=""
              onclick="changeMainImage('{{MEDIA_URL}}{{image.image_url}}')"
            />
          </div>
          {%endfor%}
        </div>
      </div>
      {% else %}
      <p>No images available</p>
      {% endif %}

      <div class="Price">
        {% if productinfo.quantity == 0 %}
          <span>Sold Out!</span>
        {% else %}
          <span class="text-red-900 dark:text-white text-3xl font-bold">
            &#36;{{productinfo.price_number}}</span>
        {% endif %}
      </div>
      <p class="text-2xl dark:text-white">
        Condition: {{productinfo.get_condition_display}}
      </p>

      <h3 class="font-bold my-4 dark:text-white">About this item</h3>
      <div class="my-2" id="description">
        <p class="font-light dark:text-white">
          {{productinfo.description_text}}
        </p>
      </div>

      {% endif%} 
    {%include '../contactapp/aboutproduct.html'%}
    </section>

    {%include "products/components/footer.html"%}

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        const mainImage = document.getElementById("mainImage");

        window.changeMainImage = function (imageUrl) {
          mainImage.setAttribute("src", imageUrl);
        };
      });
    </script>
  </body>
</html>

products/templates/products/home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Etenda Store</title>
    <meta
      name="description"
      content="Explore a curated selection of high-quality items at unbeatable prices. Discover great deals on a variety of products without compromising on quality. Shop now for incredible savings!"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static "css/output.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <script is:inline>
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      ) {
        document.documentElement.classList.add("dark");
      } else {
        document.documentElement.classList.remove("dark");
      }
    </script>
  </head>
  <body class="dark:bg-gradient-to-b dark:from-[#001d39] dark:to-black">
    {% include "products/components/header.html" %}

    <div class="p-2 max-w-screen-md mx-auto my-8" id="who">
      <h2
        class="text-center text-4xl md:text-6xl lg:text-8xl font-extrabold mb-4 dark:text-white"
      >
        Awesome Deals!
      </h2>
      <p
        class="px-5 mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-300"
      >
        If you're in the <span class="font-bold">Chicagoland Area</span>, we've
        got something special just for you! We're a small marketplace offering
        open-box and slightly used items at unbeatable prices. While some boxes
        may show signs of wear, rest assured that every product undergoes
        thorough inspection before it reaches you, ensuring top-notch quality.
        Reach out to us via our contact page, and we'll gladly arrange a meeting
        to help you find the perfect items.
      </p>
    </div>

    <section class="my-10">
      <h2
        class="ml-2 font-bold text-2xl md:text-4xl p-2 md:p-4 dark:text-white"
      >
        Our lastest arrivals
      </h2>
      {% if latest_products %}
      <ul class="h-[32rem] whitespace-nowrap overflow-x-auto w-screen mx-auto">
        {% for product in latest_products %}

        <li class="w-[350px] h-96 p-6 inline-block">
          <div
            class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-slate-950 dark:border-gray-700"
          >
            <a
              href="{% url 'products:detail' product.id %}"
              style="text-decoration: none"
            >
              <img
                class="mx-auto w-72 h-72 p-8 rounded-t-lg"
                src="{{MEDIA_URL}}{{product.images.all.0.image_url}}"
                alt="{{ product.images.all.0.alt_text}}"
              />
            </a>
            <div class="whitespace-normal h-24 px-5 pb-5 min-w-0">
              <a href="{% url 'products:detail' product.id %}">
                <h3
                  class="line-clamp-3 overflow-y-hidden h-22 text-xl font-semibold tracking-tight text-gray-900 dark:text-white"
                >
                  {{product.title_text}}
                </h3>
              </a>
            </div>
            <div class="flex items-center justify-between p-3">
              <span class="text-3xl font-bold text-gray-900 dark:text-white"
                >$ {{product.price_number}}</span
              >
              <a
                href="{% url 'products:detail' product.id %}"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                >Product Details</a
              >
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
      {% endif %}
    </section>

    {%include "products/components/footer.html"%}
  </body>
</html>

products/templates/products/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Etenda Store</title>
    <meta
      name="description"
      content="Check out all our products, Explore a selection of items at unbeatable prices. Discover great deals on a variety of products without compromising on quality. Shop now for incredible savings!"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static "css/output.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <script is:inline>
      // On page load or when changing themes, best to add inline in `head` to avoid FOUC
      if (
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
          window.matchMedia("(prefers-color-scheme: dark)").matches)
      ) {
        document.documentElement.classList.add("dark");
      } else {
        document.documentElement.classList.remove("dark");
      }
    </script>
  </head>
  <body class="dark:bg-gradient-to-b dark:from-[#001d39] dark:to-black">
    {% include "products/components/header.html" %}

    <h1
      class="mt-10 mb-8 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white"
    >
      Current Products
    </h1>

    {% if products_list %}
    <div class="max-w-5xl mx-auto mb-4">
      <ul
        class="mx-auto grid md:grid-cols-2 lg:grid-cols-3 auto-rows-min gap-12"
      >
        {% for product in products_list %}
        <li class="w-[350px] h-96 p-6 inline-block row-span-11 mx-auto">
          <div
            class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-slate-950 dark:border-gray-700"
          >
            <a
              href="{% url 'products:detail' product.id %}"
              style="text-decoration: none"
            >
            {% if forloop.counter <= 9 %}
              <img
                class="mx-auto w-72 h-72 p-8 rounded-t-lg"
                src="{{MEDIA_URL}}{{product.images.all.0.image_url}}"
                alt="{{ product.images.all.0.alt_text}}"
                
              />
              {% else %}
              <img
                class="mx-auto w-72 h-72 p-8 rounded-t-lg"
                src="{{MEDIA_URL}}{{product.images.all.0.image_url}}"
                alt="{{ product.images.all.0.alt_text}}"
                loading = "lazy"
              />
              {% endif %}
            </a>
            <div class="h-24 px-5 pb-5 min-w-0">
              <a href="{% url 'products:detail' product.id %}">
                <h3
                  class="line-clamp-3 overflow-y-hidden h-22 text-xl font-semibold tracking-tight text-gray-900 dark:text-white"
                >
                  {{product.title_text}}
                </h3>
              </a>
            </div>
            <div class="flex items-center justify-between p-3">
              <span class="text-3xl font-bold text-gray-900 dark:text-white"
                >$ {{product.price_number}}</span
              >
              <a
                href="{% url 'products:detail' product.id %}"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                >Product Details</a
              >
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
    {%else%}
    <p>No products available</p>
    {%endif%}

    <nav
      class="max-w-5xl text-center mx-auto"
      aria-label="Page navigation example"
    >
      <ul class="inline-flex -space-x-px text-sm">
        <li>
          <a
            href="?page=1"
            class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
            >First</a
          >
        </li>
        {% for i in page_obj.paginator.page_range %} 
        {% if i == page_obj.number %}
        <li>
          <a
            href="?page={{i}}"
            aria-current="page"
            class="flex items-center justify-center px-3 h-8 text-blue-600 border border-gray-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white"
            >{{i}}</a
          >
        </li>
        {% else %}
        <li>
          <a
            href="?page={{i}}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
            >{{i}}</a
          >
        </li>
        {% endif %} {% endfor %}
        <li>
          <a
            href="?page={{page_obj.paginator.num_pages}}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
            >Last</a
          >
        </li>
      </ul>
    </nav>
    {%include "products/components/footer.html"%}
  </body>
</html>

products/templates/products/search.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Etenda Store</title>
        <meta name="description" content="Search results tailored to your query. Explore a wide range of products, and resources matching your search terms. Discover the information you're looking for quickly and easily.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/output.css" %}">  
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
        <script is:inline>
            // On page load or when changing themes, best to add inline in `head` to avoid FOUC
            if (
              localStorage.getItem("color-theme") === "dark" ||
              (!("color-theme" in localStorage) &&
                window.matchMedia("(prefers-color-scheme: dark)").matches)
            ) {
              document.documentElement.classList.add("dark");
            } else {
              document.documentElement.classList.remove("dark");
            }
          </script>
        
        

    </head>
    <body style="min-height:100vh;" class="dark:bg-gradient-to-b dark:from-[#001d39] dark:to-black">

        {% include "products/components/header.html" %}

        <section class="p-2">
            <h1 class= "mt-12 mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Search Results</h1>

            {% if object_list%}
                <table class = "mx-auto max-w-screen-md" id="search-table" style="min-height:90vh;">
                
                    <tr class="">
                        <th class="dark:text-white">Item</th>
                        <th class="dark:text-white">Price</th>
                    </tr>

                {% for product in object_list %}
                    
                    <tr class="">
                        <td class = ""> <a class="dark:text-white" href={% url 'products:detail' product.id%}>{{ product.title_text }}</a></td>
                        <td class=" dark:text-white">{{ product.price_number }}</td>
                    </tr>

                {% endfor %}
                    
                </table>
                
            {% else %}
                <span> No items found</span>
            {% endif %}

            <nav class="max-w-5xl text-center mx-auto" aria-label="Page navigation example">
                <ul class=" inline-flex -space-x-px text-sm">
                    <li>
                        <a href="?page=1" class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">First</a>
                    </li>
                    {% for i in page_obj.paginator.page_range %}
                        {% if i == page_obj.number%}
                        <li>
                            <a href="?page={{i}}" aria-current="page" class="flex items-center justify-center px-3 h-8 text-blue-600 border border-gray-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{i}}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="?page={{i}}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{i}}</a>
                        </li>
                        {% endif %}
                        
                    {% endfor %}
                    <li>
                        <a href="?page={{page_obj.paginator.num_pages}}" class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Last</a>
                    </li>
                </ul>
            </nav>
        </section>

        {%include "products/components/footer.html"%}

    </body>
</html>